AWSTemplateFormatVersion: 2010-09-09
Description: >-
  opdelegates-api
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  cacheDailyDelegatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/cache_delegates/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Description: Cache daily data
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Put*
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
              Resource: "*"
      Environment:
        Variables:
          DUNE_API_KEY: !Sub "{{resolve:ssm:DUNE_API_KEY:1}}"
      Events:
        SubscriptionPopulator:
          Type: Schedule
          Properties:
            Schedule: "cron(0 3 * * ? *)"

  saveIndividualCountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/save_individual_counts/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 3008
      Timeout: 900
      Description: Save individual counts
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Put*
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
              Resource: "*"
      Environment:
        Variables:
          DUNE_API_KEY: !Sub "{{resolve:ssm:DUNE_API_KEY:1}}"
      Events:
        SubscriptionPopulator:
          Type: Schedule
          Properties:
            Schedule: "cron(0 3 * * ? *)"

  updateDelegationCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/update_delegation_csv/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 3008
      Timeout: 900
      Description: Update Delegation CSV
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Put*
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
              Resource: "*"
      Environment:
        Variables:
          DUNE_API_KEY: !Sub "{{resolve:ssm:DUNE_API_KEY:1}}"
      Events:
        SubscriptionPopulator:
          Type: Schedule
          Properties:
            Schedule: "cron(0 2 * * ? *)"

  getTopWalletsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get_top_wallets/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Description: Cache top wallets
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:Put*
                - s3:PutObject
                - s3:PutObjectAcl
                - s3:GetObject
              Resource: "*"
      Environment:
        Variables:
          DUNE_API_KEY: !Sub "{{resolve:ssm:DUNE_API_KEY:1}}"
      Events:
        SubscriptionPopulator:
          Type: Schedule
          Properties:
            Schedule: "cron(0 3 * * ? *)"

  getDailyDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get_daily_data/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Description: Get daily data from Dune Analytics
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get_daily_data/{proxy+}
            Method: any

  getDailyDelegatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/get_daily_delegates/app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 900
      Description: Get daily data from Dune Analytics
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get_daily_delegates/{proxy+}
            Method: any

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin'"
  Function:
    LoggingConfig:
      LogFormat: JSON
