name: Pipeline

# cancel if previous runs are still running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.SAM_AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.SAM_AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yml

  DEV_STACK_NAME: sam-app
  # If there are functions with "Image" PackageType in your template,
  # uncomment the line below and add "--image-repository ${DEV_IMAGE_REPOSITORY}" to
  # dev "sam package" and "sam deploy" commands.
  # DEV_IMAGE_REPOSITORY = '0123456789.dkr.ecr.region.amazonaws.com/repository-name'
  DEV_REGION: us-east-1

jobs:
  build-and-package:
    defaults:
      run:
        working-directory: opdelegates-api
    timeout-minutes: 3
    if: github.ref == 'refs/heads/dev'
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build resources
        run: |
          sam build

      - name: Assume the development pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DEV_REGION }}
          role-session-name: development-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to development artifact buckets
        run: |
          sam package \
            --region ${DEV_REGION} \
            --output-template-file packaged.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: packaged.yaml
          path: opdelegates-api/packaged.yaml

  deploy-dev:
    defaults:
      run:
        working-directory: opdelegates-api
    timeout-minutes: 5
    if: github.ref == 'refs/heads/dev'
    needs: [build-and-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/download-artifact@v3
        with:
          name: packaged.yaml

      - name: Assume the dev pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DEV_REGION }}
          role-session-name: dev-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to dev account
        run: |
          sam deploy --stack-name ${DEV_STACK_NAME} \
            --template packaged.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${DEV_REGION} \
            --no-fail-on-empty-changeset \
